<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TAOYE" ignored="0" tests="1" failures="1" timestamp="12 Dec 2018 16:16:15 GMT" time="18.254" errors="0">
  <testcase name="appTesting" time="18.163" classname="AutomationMain">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="7 &amp;gt;= 7">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 7 >= 7
at java.util.Vector.elementAt(Unknown Source)
at ElementList.get(ElementList.java:28)
at ElementList.compareInVector(ElementList.java:156)
at ElementList.addObjectToSortedList(ElementList.java:72)
at ElementList.addObjectToSortedList(ElementList.java:114)
at ElementList.addObjectToSortedList(ElementList.java:114)
at ElementList.addObjectToSortedList(ElementList.java:114)
at ElementList.sortby(ElementList.java:41)
at MWAndroidDriver.<init>(MWAndroidDriver.java:160)
at MWDriver.<init>(MWDriver.java:168)
at customizedCSVReader.readAndExecuteTestGroup(customizedCSVReader.java:115)
at AutomationMain.appTesting(AutomationMain.java:105)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- appTesting -->
</testsuite>
